In [4]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D

import time
from scipy import stats
from scipy.optimize import leastsq
import scipy.optimize as opt
from scipy.stats import norm, poisson
# from scipy.interpolate import BarycentricInterpolator, CubicSpline

import math
#import seaborn

In [5]:
def residual(t, X, y):
    ''' Quadratic function: f(x) = t[0]* x**2 + t[1]* x + t[2] '''
    return y-(t[0]* x**2 + t[1]*x + t[2])

def residual2(t, X, y):
    ''' function: f(x) = t0*sin(t1* x) + t2  '''
    print( t[0], t[1])
    return y-(t[0]* np.sin(t[1]* x) + t[2])

In [ ]:
# x ** x        x > 0
# (-x) ** (-x)  x < 0
def f(x):
    y = np.ones_like(x)
    i = x > 0
    y[i] = np.power(x[i], x[i])
    i = x < 0
    y[i] = np.power(-x[i], -x[i])
    return y

In [7]:
a = np.arange(0, 60, 10).reshape((-1, 1)) + np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [25]:
L = [1,2,3,4,5,6]
print(L)
a = np.array(L)
print(a)
print(a.shape)


b = np.array([[1,2,3,4,], [5,6,7,8],[9,10,11,12]])
print(b)
print(b.shape)

# change shape: 
b.shape= [4,3]
print(b)

# if shape have a dim =-1, will calcualte base on other dim
b.shape =[2,-1]
print(b)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
(6,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
