In [4]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

import time
from scipy import stats
from scipy.optimize import leastsq
import scipy.optimize as opt
from scipy.stats import norm, poisson
# from scipy.interpolate import BarycentricInterpolator, CubicSpline

import math
#import seaborn

In [5]:
def residual(t, X, y):
    ''' Quadratic function: f(x) = t[0]* x**2 + t[1]* x + t[2] '''
    return y-(t[0]* x**2 + t[1]*x + t[2])

def residual2(t, X, y):
    ''' function: f(x) = t0*sin(t1* x) + t2  '''
    print( t[0], t[1])
    return y-(t[0]* np.sin(t[1]* x) + t[2])

In [ ]:
# x ** x        x > 0
# (-x) ** (-x)  x < 0
def f(x):
    y = np.ones_like(x)
    i = x > 0
    y[i] = np.power(x[i], x[i])
    i = x < 0
    y[i] = np.power(-x[i], -x[i])
    return y

## 1. Numpy array

In [7]:
a = np.arange(0, 60, 10).reshape((-1, 1)) + np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [36]:
L = [1,2,3,4,5,6]
print(L)
a = np.array(L)
print(a)
print(a.shape)


b = np.array([[1,2,3,4,], [5,6,7,8],[9,10,11,12]], dtype= np.float)
print(b)
print(b.shape)

f = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.complex)
print(f)    

# change data type
d = b.astype(np.int)
print(d)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
(6,)
[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]]
(3, 4)
[[  1.+0.j   2.+0.j   3.+0.j   4.+0.j]
 [  5.+0.j   6.+0.j   7.+0.j   8.+0.j]
 [  9.+0.j  10.+0.j  11.+0.j  12.+0.j]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:

# change shape: 
b.shape= [4,3]
print(b)

# if shape have a dim =-1, will calcualte base on other dim
b.shape =[2,-1]
print(b)

# reshape: create a new array linked to the original array
c= b.reshape((4,-1))
print(c)

# if we change numbers in b, c will also be changed
b[0][1] = 20
print(c)


[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]]
[[  1.   2.   3.   4.   5.   6.]
 [  7.   8.   9.  10.  11.  12.]]
[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]]
[[  1.  20.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]]


## 2. Functions

In [43]:
a = np.arange(start= 1, stop= 10, step= 0.5, dtype= float)
a

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [48]:
? np.logspace

In [47]:
b = np.linspace(start =1 , stop=10 , num= 10)
print(b)
c = np.linspace(start =1 , stop=10 , num= 10, endpoint= False)
print(c)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1]


In [55]:
# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
# Return numbers spaced evenly on a log scale.

d = np.logspace(start = 1, stop= 2, num= 9, endpoint= True)
print(d)

d = np.logspace(start = 0, stop= 10, num= 11, base=2 , endpoint= True, dtype= int)
print(d)

[  10.           13.33521432   17.7827941    23.71373706   31.6227766
   42.16965034   56.23413252   74.98942093  100.        ]
[   1    2    4    8   16   32   64  128  256  512 1024]


In [57]:
# frombuffer, fromstring, fromfile

s = 'dsfabrd'
g = np.fromstring(s, dtype= np.int8)
print(g)

[100 115 102  97  98 114 100]


## 3. Read from array 

In [64]:
a = np.arange(10)
print(a)
print(a[3])
print(a[:5])
print(a[3:6])    # slicing
print(a[1:9:2])  # include start, exclude end
print(a[::-1])   # reverse
# change value of slicing
a[1:4] = 10, 20,30
print(a)

# change value of a slice, the original values will also be changed
b = a[2:5]
b[0] = 200
print(a)

[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2 3 4]
[3 4 5]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]
[ 0 10 20 30  4  5  6  7  8  9]
[  0  10 200  30   4   5   6   7   8   9]


In [68]:
# slice an array with another slice
a = np.logspace(start= 0, stop= 9, num= 10, base= 2)
print(a)
i = np.arange(start= 0, stop= 10, step= 2)
print(i)
print(a[i])

[   1.    2.    4.    8.   16.   32.   64.  128.  256.  512.]
[0 2 4 6 8]
[   1.    4.   16.   64.  256.]


In [79]:
# 10 U(0,1) random variables
a = np.random.rand(10)
print(a)

b= a[a>0.5]
print(b)

a[a>0.5] = 0.5
print(b)          # b remains unchanged

[ 0.93531936  0.73115264  0.02466121  0.08472319  0.7255384   0.40345048
  0.90327348  0.69152195  0.53360324  0.66308601]
[ 0.93531936  0.73115264  0.7255384   0.90327348  0.69152195  0.53360324
  0.66308601]
[ 0.93531936  0.73115264  0.7255384   0.90327348  0.69152195  0.53360324
  0.66308601]


### Slicing 2D arrays

In [97]:
a = np.arange(start=0, stop= 60, step=10).reshape((-1,1))+ np.arange(0,6)
print(a)

print(a[[1,2,3],[2,3,4]])
print(a[4, [2,3,4]])
print(a[4:, [2,3,4]])

i = np.array([True, False, True, False, False, True])
print(a[i]) # select rows
print(a[i,3])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[12 23 34]
[42 43 44]
[[42 43 44]
 [52 53 54]]
[[ 0  1  2  3  4  5]
 [20 21 22 23 24 25]
 [50 51 52 53 54 55]]
[ 3 23 53]


In [ ]:


    # 4.1 numpy与Python数学库的时间比较
    # for j in np.logspace(0, 7, 10):
    #     j = int(j)
    #     x = np.linspace(0, 10, j)
    #     start = time.clock()
    #     y = np.sin(x)
    #     t1 = time.clock() - start
    #
    #     x = x.tolist()
    #     start = time.clock()
    #     for i, t in enumerate(x):
    #         x[i] = math.sin(t)
    #     t2 = time.clock() - start
    #     print j, ": ", t1, t2, t2/t1

    # 4.2 元素去重
    # 4.2.1直接使用库函数
    # a = np.array((1, 2, 3, 4, 5, 5, 7, 3, 2, 2, 8, 8))
    # print '原始数组：', a
    # # # 使用库函数unique
    # b = np.unique(a)
    # print '去重后：', b
    # # # 4.2.2 二维数组的去重，结果会是预期的么？
    # c = np.array(((1, 2), (3, 4), (5, 6), (1, 3), (3, 4), (7, 6)))
    # print u'二维数组：\n', c
    # print '去重后：', np.unique(c)
    # # # 4.2.3 方案1：转换为虚数
    # # r, i = np.split(c, (1, ), axis=1)
    # # x = r + i * 1j
    # x = c[:, 0] + c[:, 1] * 1j
    # print '转换成虚数：', x
    # print '虚数去重后：', np.unique(x)
    # print np.unique(x, return_index=True)   # 思考return_index的意义
    # idx = np.unique(x, return_index=True)[1]
    # print '二维数组去重：\n', c[idx]
    # # 4.2.3 方案2：利用set
    # print '去重方案2：\n', np.array(list(set([tuple(t) for t in c])))

    # 4.3 stack and axis
    # a = np.arange(1, 10).reshape((3, 3))
    # b = np.arange(11, 20).reshape((3, 3))
    # c = np.arange(101, 110).reshape((3, 3))
    # print 'a = \n', a
    # print 'b = \n', b
    # print 'c = \n', c
    # print 'axis = 0 \n', np.stack((a, b, c), axis=0)
    # print 'axis = 1 \n', np.stack((a, b, c), axis=1)
    # print 'axis = 2 \n', np.stack((a, b, c), axis=2)

    # a = np.arange(1, 10).reshape(3,3)
    # print a
    # b = a + 10
    # print b
    # print np.dot(a, b)
    # print a * b

    # a = np.arange(1, 10)
    # print a
    # b = np.arange(20,25)
    # print b
    # print np.concatenate((a, b))